version: '3.8'

services:
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001
    container_name: backend
    # ports:
    #   - "8001:8001"
    expose:
      - 8001
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - static:/backend-workdir/static
      - media:/backend-workdir/img
  
  db:
    image: postgres:latest 
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - local_pgdata1:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static:/backend-workdir/static/
      - media:/backend-workdir/img
    depends_on:
      - backend

volumes:  
  local_pgdata1:  
  static:
  media:
